language: c
compiler:
  - gcc
  - clang
# a shame, no test target in Makefile yet; for now, try building the .deb
script: make package
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcurl3 libcurl4-gnutls-dev libgnutls-dev git curl vim-common libcurl4-gnutls-dev libgnutls-dev build-essential dh-make devscripts
